apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    tier: frontend
    bu: person
  name: person-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      bu: person
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        tier: frontend
        bu: person
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
