apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simple-webapp-color
  name: simple-webapp-color
spec:
  securityContext: # PodSecurityContext
    runAsUser: 1000
      # capabilities:
      # add:
      # - "MAC_ADMIN"
  containers:
  - image: simple-webapp-color
    name: simple-webapp-color
    ports:
    - containerPort: 8080
    securityContext: # SecurityContext
      capabilities:
        add: ["MAC_ADMIN"]
