apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simple-webapp-color
  name: simple-webapp-color
spec:
  containers:
  - image: kodekloud/webapp-color
    name: simple-webapp-color
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: app-color
