apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simple-webapp-color-green
  name: simple-webapp-color-green
spec:
  containers:
  - image: kodekloud/webapp-color
    name: simple-webapp-color-green
    ports:
    - containerPort: 8080
    env:
    - name: APP_COLOR
      valueFrom:
        configMapKeyRef:
          name: app-color-green
          key: APP_COLOR
